### ISSUE TITLE
MongoDb connection failed to connect to server [localhost:27017] 

### ISSUE THREAD

**Issue by jocelinqueau** [FrontendMasters/api-design-node-v3#76]
During my challenges i get.
I do have downgrade my node to 8, without that i wouldn't install and change some yarn call to node, because i don't have yarn.
I may have miss some configuration, but from what i understood, the connection to the db wasn't affecting the test, so it's a bit weird.

when i test i have 
`
> cross-env NODE_ENV=testing jest --forceExit --detectOpenHandles  --silent "controllers"

(node:25710) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dropDatabase' of undefined
(node:25710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
`
when i try to dev, it delete my build package so i have a
`
rror: Cannot find module 'RELATIVEPATHOFMYDESKTOP/api-design-node-v3/dist/index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-design-v3@1.0.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
`
if i try to run build then start i have 
`

{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/jocelinqueau/Desktop/Dev/frontendMasters/api-design-node-v3/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/Users/jocelinqueau/Desktop/Dev/frontendMasters/api-design-node-v3/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/Users/jocelinqueau/Desktop/Dev/frontendMasters/api-design-node-v3/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:73:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
`

**Comment by jocelinqueau** [comment]
Actually i think i have to run mongo in local
